### ISSUE TITLE
Bug in do_SRA_sX

### ISSUE THREAD

**Issue by saul-rodriguez** [sc0ty/picoblaze#1]
Hi!
Thanks for a great work on this simulator. I like it a lot.

I found a bug in the SRA instruction. The SRA rotation requires to insert the previous carry flag. However, the flag is currently updated with its new value before the rotation takes place (Xlinix UG129 manual, page 107). My correction is the following:
```
void Instruction::do_SRA_sX(Cpu &cpu)
{
    uint8_t rx = getRegX(cpu);
    uint8_t temp_cf;

    temp_cf = rx & 1;
    //cpu.flags.cf = rx & 1;

    rx >>= 1;
    rx |= (cpu.flags.cf << 7);

    cpu.flags.cf = temp_cf;

    setRegX(cpu, rx);
    cpu.flags.zf = (rx == 0);
}
```

**Comment by sc0ty** [comment]
Thanks.
I think SLA sX has the same issue:
```
void Instruction::do_SLA_sX(Cpu &cpu)
{
    uint8_t rx = getRegX(cpu);
    cpu.flags.cf = rx & 0x80;

    rx <<= 1;
    rx |= cpu.flags.cf;

    setRegX(cpu, rx);
    cpu.flags.zf = (rx == 0);
}
```

**Comment by saul-rodriguez** [comment]
Thanks,
Yes, it has the same problem. I solved it in the same way:

void Instruction::do_SLA_sX(Cpu &cpu)
{
    uint8_t rx = getRegX(cpu);
    uint8_t temp_cf;    
	
    temp_cf = rx & 0x80;
    //cpu.flags.cf = rx & 0x80;

    rx <<= 1;
    rx |= cpu.flags.cf;

    cpu.flags.cf = temp_cf;

    setRegX(cpu, rx);
    cpu.flags.zf = (rx == 0);
}

**Comment by sc0ty** [comment]
Fixed, could you verify it? I don't have Picoblaze compiler at hand to do it myself.

**Comment by saul-rodriguez** [comment]
Hi,
both instructions were successfully tested by using the following code:

        LOAD s0, f0
	LOAD S1, 00	
	SLA s0
	SLA s1
	LOAD s0, 0f
	LOAD s1, 0
	SRA s0
	SRA s1	

Many thanks!
